// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © bobina22
//@version=5
indicator("Swings", shorttitle="Swings", format=format.price, precision=0, overlay=true)
n = 1
swing_high = high[n+1] < high[n] and high[n]> high[n-1]
swing_low = low[n+1] > low[n] and low[n] < low[n-1]

plotshape(swing_low, style=shape.triangledown, location=location.belowbar, offset=-n, color=color.new(#F44336, 75), size=size.tiny)
plotshape(swing_high, style=shape.triangleup,   location=location.abovebar, offset=-n, color=color.new(#009688, 75), size=size.tiny)
